/**
 * Barrel file exporting ALL source plugin modules.
 *
 * Import this in JobsModule to register all 160+ source plugins:
 *   import { ALL_SOURCE_MODULES } from '@ever-jobs/plugin-sources';
 *   @Module({ imports: [PluginModule, ...ALL_SOURCE_MODULES] })
 *
 * @auto-generated by scripts/gen-barrel.ps1
 */
import { FourDayWeekModule } from './source-4dayweek';
import { AcademiccareersModule } from './source-academiccareers';
import { AdzunaModule } from './source-adzuna';
import { AndroidjobsModule } from './source-androidjobs';
import { ArbeitnowModule } from './source-arbeitnow';
import { ArbeitsagenturModule } from './source-arbeitsagentur';
import { AdpModule } from './source-ats-adp';
import { AshbyModule } from './source-ats-ashby';
import { AvatureModule } from './source-ats-avature';
import { BambooHRModule } from './source-ats-bamboohr';
import { BreezyHRModule } from './source-ats-breezyhr';
import { BullhornModule } from './source-ats-bullhorn';
import { ComeetModule } from './source-ats-comeet';
import { CrelateModule } from './source-ats-crelate';
import { DeelModule } from './source-ats-deel';
import { FountainModule } from './source-ats-fountain';
import { FreshteamModule } from './source-ats-freshteam';
import { GemModule } from './source-ats-gem';
import { GreenhouseModule } from './source-ats-greenhouse';
import { HiringThingModule } from './source-ats-hiringthing';
import { HomerunModule } from './source-ats-homerun';
import { IcimsModule } from './source-ats-icims';
import { ISmartRecruitModule } from './source-ats-ismartrecruit';
import { JazzHRModule } from './source-ats-jazzhr';
import { JobScoreModule } from './source-ats-jobscore';
import { JobviteModule } from './source-ats-jobvite';
import { JobylonModule } from './source-ats-jobylon';
import { JoinComModule } from './source-ats-joincom';
import { LeverModule } from './source-ats-lever';
import { LoxoModule } from './source-ats-loxo';
import { ManatalModule } from './source-ats-manatal';
import { MercorModule } from './source-ats-mercor';
import { OracleModule } from './source-ats-oracle';
import { PaylocityModule } from './source-ats-paylocity';
import { PersonioModule } from './source-ats-personio';
import { PhenomModule } from './source-ats-phenom';
import { PinpointModule } from './source-ats-pinpoint';
import { RecruiteeModule } from './source-ats-recruitee';
import { RecruiterflowModule } from './source-ats-recruiterflow';
import { RipplingModule } from './source-ats-rippling';
import { SmartRecruitersModule } from './source-ats-smartrecruiters';
import { SuccessFactorsModule } from './source-ats-successfactors';
import { TalentLyftModule } from './source-ats-talentlyft';
import { TaleoModule } from './source-ats-taleo';
import { TeamtailorModule } from './source-ats-teamtailor';
import { TrakstarModule } from './source-ats-trakstar';
import { UkgModule } from './source-ats-ukg';
import { WorkableModule } from './source-ats-workable';
import { WorkdayModule } from './source-ats-workday';
import { AuthenticJobsModule } from './source-authenticjobs';
import { BaytModule } from './source-bayt';
import { BDJobsModule } from './source-bdjobs';
import { BerlinStartupJobsModule } from './source-berlinstartupjobs';
import { BuiltInModule } from './source-builtin';
import { CanadaJobBankModule } from './source-canadajobbank';
import { CareerBuilderModule } from './source-careerbuilder';
import { CareerJetModule } from './source-careerjet';
import { CareerOneStopModule } from './source-careeronestop';
import { ClojurejobsModule } from './source-clojurejobs';
import { AccuWeatherModule } from './source-company-accuweather';
import { AciLearningModule } from './source-company-acilearning';
import { AckermannGroupModule } from './source-company-ackermanngroup';
import { AcluModule } from './source-company-aclu';
import { AcogModule } from './source-company-acog';
import { AcommerceModule } from './source-company-acommerce';
import { AcpModule } from './source-company-acp';
import { AcquiaModule } from './source-company-acquia';
import { AcrisureInnovationModule } from './source-company-acrisureinnovation';
import { AdyenModule } from './source-company-adyen';
import { AffirmModule } from './source-company-affirm';
import { AirbnbModule } from './source-company-airbnb';
import { AirtableModule } from './source-company-airtable';
import { AlmaModule } from './source-company-alma';
import { AmazonModule } from './source-company-amazon';
import { AmplitudeModule } from './source-company-amplitude';
import { AnthropicModule } from './source-company-anthropic';
import { AppleModule } from './source-company-apple';
import { AsanaModule } from './source-company-asana';
import { AssemblyAIModule } from './source-company-assemblyai';
import { AttentiveModule } from './source-company-attentive';
import { AxonModule } from './source-company-axon';
import { BandwidthModule } from './source-company-bandwidth';
import { BeamModule } from './source-company-beam';
import { BenevityModule } from './source-company-benevity';
import { BettermentModule } from './source-company-betterment';
import { BigIdModule } from './source-company-bigid';
import { BillcomModule } from './source-company-billcom';
import { BirdModule } from './source-company-bird';
import { BitgoModule } from './source-company-bitgo';
import { BitwardenModule } from './source-company-bitwarden';
import { BlendModule } from './source-company-blend';
import { BloomreachModule } from './source-company-bloomreach';
import { BlockModule } from './source-company-block';
import { BobbieModule } from './source-company-bobbie';
import { BoeingModule } from './source-company-boeing';
import { BranchModule } from './source-company-branch';
import { BrazeModule } from './source-company-braze';
import { BrexModule } from './source-company-brex';
import { BuildkiteModule } from './source-company-buildkite';
import { CalendlyModule } from './source-company-calendly';
import { CameoModule } from './source-company-cameo';
import { CartaModule } from './source-company-carta';
import { CelonisModule } from './source-company-celonis';
import { CerebralModule } from './source-company-cerebral';
import { ChainguardModule } from './source-company-chainguard';
import { CheckrModule } from './source-company-checkr';
import { ChimeModule } from './source-company-chime';
import { CircleCIModule } from './source-company-circleci';
import { ClasspassModule } from './source-company-classpass';
import { CloudflareModule } from './source-company-cloudflare';
import { CoalitionModule } from './source-company-coalition';
import { CoinbaseModule } from './source-company-coinbase';
import { CollectiveHealthModule } from './source-company-collectivehealth';
import { ComplyAdvantageModule } from './source-company-complyadvantage';
import { ConstantContactModule } from './source-company-constantcontact';
import { ContentfulModule } from './source-company-contentful';
import { ConvivaModule } from './source-company-conviva';
import { CourseraModule } from './source-company-coursera';
import { CrestaModule } from './source-company-cresta';
import { CriblModule } from './source-company-cribl';
import { CursorModule } from './source-company-cursor';
import { DatabricksModule } from './source-company-databricks';
import { DatacampModule } from './source-company-datacamp';
import { DatadogModule } from './source-company-datadog';
import { DeepmindModule } from './source-company-deepmind';
import { DialpadModule } from './source-company-dialpad';
import { DescopeModule } from './source-company-descope';
import { DescriptModule } from './source-company-descript';
import { DiscordModule } from './source-company-discord';
import { DollarShaveClubModule } from './source-company-dollarshaveclub';
import { DoorDashModule } from './source-company-doordash';
import { DoximityModule } from './source-company-doximity';
import { DremioModule } from './source-company-dremio';
import { DropboxModule } from './source-company-dropbox';
import { DuolingoModule } from './source-company-duolingo';
import { EarnestModule } from './source-company-earnest';
import { ElasticModule } from './source-company-elastic';
import { EpicgamesModule } from './source-company-epicgames';
import { ExpressvpnModule } from './source-company-expressvpn';
import { FairmarkitModule } from './source-company-fairmarkit';
import { FaireModule } from './source-company-faire';
import { FastlyModule } from './source-company-fastly';
import { FigmaModule } from './source-company-figma';
import { FivetranModule } from './source-company-fivetran';
import { FlexportModule } from './source-company-flexport';
import { FormlabsModule } from './source-company-formlabs';
import { FoundersModule } from './source-company-founders';
import { FoxModule } from './source-company-fox';
import { FubotvModule } from './source-company-fubotv';
import { GitlabModule } from './source-company-gitlab';
import { GlossierModule } from './source-company-glossier';
import { GocardlessModule } from './source-company-gocardless';
import { GofundmeModule } from './source-company-gofundme';
import { GoogleCareersModule } from './source-company-google';
import { GustoModule } from './source-company-gusto';
import { HelloFreshModule } from './source-company-hellofresh';
import { HoneycombModule } from './source-company-honeycomb';
import { IbmModule } from './source-company-ibm';
import { IndigoModule } from './source-company-indigo';
import { InstabaseModule } from './source-company-instabase';
import { InstacartModule } from './source-company-instacart';
import { IntercomModule } from './source-company-intercom';
import { IterableModule } from './source-company-iterable';
import { JustworksModule } from './source-company-justworks';
import { KlaviyoModule } from './source-company-klaviyo';
import { LabelboxModule } from './source-company-labelbox';
import { LatticeModule } from './source-company-lattice';
import { LaunchdarklyModule } from './source-company-launchdarkly';
import { LookoutModule } from './source-company-lookout';
import { LyftModule } from './source-company-lyft';
import { MarkforgedModule } from './source-company-markforged';
import { MarqetaModule } from './source-company-marqeta';
import { MasterclassModule } from './source-company-masterclass';
import { MavenModule } from './source-company-maven';
import { MavenclinicModule } from './source-company-mavenclinic';
import { MelioModule } from './source-company-melio';
import { MercuryModule } from './source-company-mercury';
import { MetaModule } from './source-company-meta';
import { MicrosoftModule } from './source-company-microsoft';
import { MisfitsMarketModule } from './source-company-misfitsmarket';
import { MixpanelModule } from './source-company-mixpanel';
import { ModernHealthModule } from './source-company-modernhealth';
import { MongoDbModule } from './source-company-mongodb';
import { MonzoModule } from './source-company-monzo';
import { N26Module } from './source-company-n26';
import { NetflixModule } from './source-company-netflix';
import { NetlifyModule } from './source-company-netlify';
import { NetskopeModule } from './source-company-netskope';
import { NewRelicModule } from './source-company-newrelic';
import { NvidiaModule } from './source-company-nvidia';
import { OktaModule } from './source-company-okta';
import { OpenAIModule } from './source-company-openai';
import { OpendoorModule } from './source-company-opendoor';
import { OscarModule } from './source-company-oscar';
import { OtterModule } from './source-company-otter';
import { PagerdutyModule } from './source-company-pagerduty';
import { PelotonModule } from './source-company-peloton';
import { PendoModule } from './source-company-pendo';
import { PinterestModule } from './source-company-pinterest';
import { PlaidModule } from './source-company-plaid';
import { PlanetScaleModule } from './source-company-planetscale';
import { PostmanModule } from './source-company-postman';
import { PostscriptModule } from './source-company-postscript';
import { QuanataModule } from './source-company-quanata';
import { RampNetworkModule } from './source-company-rampnetwork';
import { RechargeModule } from './source-company-recharge';
import { RedditModule } from './source-company-reddit';
import { RobinhoodModule } from './source-company-robinhood';
import { RobloxModule } from './source-company-roblox';
import { SamsaraModule } from './source-company-samsara';
import { ScaleaiModule } from './source-company-scaleai';
import { ScopelyModule } from './source-company-scopely';
import { SezzleModule } from './source-company-sezzle';
import { ShopmonkeyModule } from './source-company-shopmonkey';
import { SimplisafeModule } from './source-company-simplisafe';
import { SoFiModule } from './source-company-sofi';
import { SquarespaceModule } from './source-company-squarespace';
import { StarburstModule } from './source-company-starburst';
import { StitchfixModule } from './source-company-stitchfix';
import { StockXModule } from './source-company-stockx';
import { StripeModule } from './source-company-stripe';
import { SweetgreenModule } from './source-company-sweetgreen';
import { SymphonyModule } from './source-company-symphony';
import { TatariModule } from './source-company-tatari';
import { TextioModule } from './source-company-textio';
import { TikTokModule } from './source-company-tiktok';
import { ToastModule } from './source-company-toast';
import { TwilioModule } from './source-company-twilio';
import { TwitchModule } from './source-company-twitch';
import { TypeformModule } from './source-company-typeform';
import { UberModule } from './source-company-uber';
import { UdemyModule } from './source-company-udemy';
import { VercelModule } from './source-company-vercel';
import { VonageModule } from './source-company-vonage';
import { WebflowModule } from './source-company-webflow';
import { XaiModule } from './source-company-xai';
import { ZoomModule } from './source-company-zoom';
import { ZoomInfoModule } from './source-company-zoominfo';
import { ConservationJobsModule } from './source-conservationjobs';
import { CoroflotModule } from './source-coroflot';
import { CrunchboardModule } from './source-crunchboard';
import { CryptocurrencyJobsModule } from './source-cryptocurrencyjobs';
import { CryptoJobsListModule } from './source-cryptojobslist';
import { DevITJobsModule } from './source-devitjobs';
import { DevopsjobsModule } from './source-devopsjobs';
import { DiceModule } from './source-dice';
import { DjinniModule } from './source-djinni';
import { DribbbleModule } from './source-dribbble';
import { DrupalJobsModule } from './source-drupaljobs';
import { DuunitoriModule } from './source-duunitori';
import { EchoJobsModule } from './source-echojobs';
import { EcojobsModule } from './source-ecojobs';
import { ElixirJobsModule } from './source-elixirjobs';
import { EurojobsModule } from './source-eurojobs';
import { ExaModule } from './source-exa';
import { FindWorkModule } from './source-findwork';
import { FossJobsModule } from './source-fossjobs';
import { FranceTravailModule } from './source-francetravail';
import { FreelancerComModule } from './source-freelancercom';
import { FunctionalworksModule } from './source-functionalworks';
import { GermantechjobsModule } from './source-germantechjobs';
import { GetOnBoardModule } from './source-getonboard';
import { GlassdoorModule } from './source-glassdoor';
import { GolangJobsModule } from './source-golangjobs';
import { GoogleModule } from './source-google';
import { GreenJobsBoardModule } from './source-greenjobsboard';
import { GuardianjobsModule } from './source-guardianjobs';
import { HabrcareerModule } from './source-habrcareer';
import { HackerNewsModule } from './source-hackernews';
import { HasJobModule } from './source-hasjob';
import { HeadhunterModule } from './source-headhunter';
import { HigherEdJobsModule } from './source-higheredjobs';
import { HimalayasModule } from './source-himalayas';
import { IcrunchdataModule } from './source-icrunchdata';
import { IndeedModule } from './source-indeed';
import { InfoJobsModule } from './source-infojobs';
import { IosdevjobsModule } from './source-iosdevjobs';
import { JobDataApiModule } from './source-jobdataapi';
import { JobicyModule } from './source-jobicy';
import { JobindexModule } from './source-jobindex';
import { JobsAcUkModule } from './source-jobsacuk';
import { JobsChModule } from './source-jobsch';
import { JobsdbModule } from './source-jobsdb';
import { JobsInJapanModule } from './source-jobsinjapan';
import { JobspressoModule } from './source-jobspresso';
import { JobstreetModule } from './source-jobstreet';
import { JobTechDevModule } from './source-jobtechdev';
import { JoinRiseModule } from './source-joinrise';
import { JoobleModule } from './source-jooble';
import { LandingJobsModule } from './source-landingjobs';
import { LaraJobsModule } from './source-larajobs';
import { LinkedInModule } from './source-linkedin';
import { MonsterModule } from './source-monster';
import { MycareersfutureModule } from './source-mycareersfuture';
import { NaukriModule } from './source-naukri';
import { NavJobsModule } from './source-navjobs';
import { NoDeskModule } from './source-nodesk';
import { NoFluffJobsModule } from './source-nofluffjobs';
import { OpensourcedesignjobsModule } from './source-opensourcedesignjobs';
import { PowertoflyModule } from './source-powertofly';
import { PyJobsModule } from './source-pyjobs';
import { PythonJobsModule } from './source-pythonjobs';
import { RailsJobsModule } from './source-railsjobs';
import { RealWorkFromAnywhereModule } from './source-realworkfromanywhere';
import { ReedModule } from './source-reed';
import { ReliefWebModule } from './source-reliefweb';
import { RemotefirstjobsModule } from './source-remotefirstjobs';
import { RemoteOkModule } from './source-remoteok';
import { RemotiveModule } from './source-remotive';
import { SimplyHiredModule } from './source-simplyhired';
import { SnagajobModule } from './source-snagajob';
import { StartupJobsModule } from './source-startupjobs';
import { StepStoneModule } from './source-stepstone';
import { SwissdevjobsModule } from './source-swissdevjobs';
import { TalrooModule } from './source-talroo';
import { TechcareersModule } from './source-techcareers';
import { TeslaModule } from './source-tesla';
import { TheMuseModule } from './source-themuse';
import { UndpJobsModule } from './source-undpjobs';
import { UpworkModule } from './source-upwork';
import { UsajobsModule } from './source-usajobs';
import { VirtualVocationsModule } from './source-virtualvocations';
import { VueJobsModule } from './source-vuejobs';
import { Web3CareerModule } from './source-web3career';
import { WellfoundModule } from './source-wellfound';
import { WeWorkRemotelyModule } from './source-weworkremotely';
import { WordPressJobsModule } from './source-wordpressjobs';
import { WorkingNomadsModule } from './source-workingnomads';
import { ZipRecruiterModule } from './source-ziprecruiter';

export const ALL_SOURCE_MODULES = [
  FourDayWeekModule,
  AcademiccareersModule,
  AdzunaModule,
  AndroidjobsModule,
  ArbeitnowModule,
  ArbeitsagenturModule,
  AdpModule,
  AshbyModule,
  AvatureModule,
  BambooHRModule,
  BreezyHRModule,
  BullhornModule,
  ComeetModule,
  CrelateModule,
  DeelModule,
  FountainModule,
  FreshteamModule,
  GemModule,
  GreenhouseModule,
  HiringThingModule,
  HomerunModule,
  IcimsModule,
  ISmartRecruitModule,
  JazzHRModule,
  JobScoreModule,
  JobviteModule,
  JobylonModule,
  JoinComModule,
  LeverModule,
  LoxoModule,
  ManatalModule,
  MercorModule,
  OracleModule,
  PaylocityModule,
  PersonioModule,
  PhenomModule,
  PinpointModule,
  RecruiteeModule,
  RecruiterflowModule,
  RipplingModule,
  SmartRecruitersModule,
  SuccessFactorsModule,
  TalentLyftModule,
  TaleoModule,
  TeamtailorModule,
  TrakstarModule,
  UkgModule,
  WorkableModule,
  WorkdayModule,
  AuthenticJobsModule,
  BaytModule,
  BDJobsModule,
  BerlinStartupJobsModule,
  BuiltInModule,
  CanadaJobBankModule,
  CareerBuilderModule,
  CareerJetModule,
  CareerOneStopModule,
  ClojurejobsModule,
  AccuWeatherModule,
  AciLearningModule,
  AckermannGroupModule,
  AcluModule,
  AcogModule,
  AcommerceModule,
  AcpModule,
  AcquiaModule,
  AcrisureInnovationModule,
  AdyenModule,
  AffirmModule,
  AirbnbModule,
  AirtableModule,
  AlmaModule,
  AmazonModule,
  AmplitudeModule,
  AnthropicModule,
  AppleModule,
  AsanaModule,
  AssemblyAIModule,
  AttentiveModule,
  AxonModule,
  BandwidthModule,
  BeamModule,
  BenevityModule,
  BettermentModule,
  BigIdModule,
  BillcomModule,
  BirdModule,
  BitgoModule,
  BitwardenModule,
  BlendModule,
  BloomreachModule,
  BlockModule,
  BobbieModule,
  BoeingModule,
  BranchModule,
  BrazeModule,
  BrexModule,
  BuildkiteModule,
  CalendlyModule,
  CameoModule,
  CartaModule,
  CelonisModule,
  CerebralModule,
  ChainguardModule,
  CheckrModule,
  ChimeModule,
  CircleCIModule,
  ClasspassModule,
  CloudflareModule,
  CoalitionModule,
  CoinbaseModule,
  CollectiveHealthModule,
  ComplyAdvantageModule,
  ConstantContactModule,
  ContentfulModule,
  ConvivaModule,
  CourseraModule,
  CrestaModule,
  CriblModule,
  CursorModule,
  DatabricksModule,
  DatacampModule,
  DatadogModule,
  DeepmindModule,
  DialpadModule,
  DescopeModule,
  DescriptModule,
  DiscordModule,
  DollarShaveClubModule,
  DoorDashModule,
  DoximityModule,
  DremioModule,
  DropboxModule,
  DuolingoModule,
  EarnestModule,
  ElasticModule,
  EpicgamesModule,
  ExpressvpnModule,
  FairmarkitModule,
  FaireModule,
  FastlyModule,
  FigmaModule,
  FivetranModule,
  FlexportModule,
  FormlabsModule,
  FoundersModule,
  FoxModule,
  FubotvModule,
  GitlabModule,
  GlossierModule,
  GocardlessModule,
  GofundmeModule,
  GoogleCareersModule,
  GustoModule,
  HelloFreshModule,
  HoneycombModule,
  IbmModule,
  IndigoModule,
  InstabaseModule,
  InstacartModule,
  IntercomModule,
  IterableModule,
  JustworksModule,
  KlaviyoModule,
  LabelboxModule,
  LatticeModule,
  LaunchdarklyModule,
  LookoutModule,
  LyftModule,
  MarkforgedModule,
  MarqetaModule,
  MasterclassModule,
  MavenModule,
  MavenclinicModule,
  MelioModule,
  MercuryModule,
  MetaModule,
  MicrosoftModule,
  MisfitsMarketModule,
  MixpanelModule,
  ModernHealthModule,
  MongoDbModule,
  MonzoModule,
  N26Module,
  NetflixModule,
  NetlifyModule,
  NetskopeModule,
  NewRelicModule,
  NvidiaModule,
  OktaModule,
  OpenAIModule,
  OpendoorModule,
  OscarModule,
  OtterModule,
  PagerdutyModule,
  PelotonModule,
  PendoModule,
  PinterestModule,
  PlaidModule,
  PlanetScaleModule,
  PostmanModule,
  PostscriptModule,
  QuanataModule,
  RampNetworkModule,
  RechargeModule,
  RedditModule,
  RobinhoodModule,
  RobloxModule,
  SamsaraModule,
  ScaleaiModule,
  ScopelyModule,
  SezzleModule,
  ShopmonkeyModule,
  SimplisafeModule,
  SoFiModule,
  SquarespaceModule,
  StarburstModule,
  StitchfixModule,
  StockXModule,
  StripeModule,
  SweetgreenModule,
  SymphonyModule,
  TatariModule,
  TextioModule,
  TikTokModule,
  ToastModule,
  TwilioModule,
  TwitchModule,
  TypeformModule,
  UberModule,
  UdemyModule,
  VercelModule,
  VonageModule,
  WebflowModule,
  XaiModule,
  ZoomModule,
  ZoomInfoModule,
  ConservationJobsModule,
  CoroflotModule,
  CrunchboardModule,
  CryptocurrencyJobsModule,
  CryptoJobsListModule,
  DevITJobsModule,
  DevopsjobsModule,
  DiceModule,
  DjinniModule,
  DribbbleModule,
  DrupalJobsModule,
  DuunitoriModule,
  EchoJobsModule,
  EcojobsModule,
  ElixirJobsModule,
  EurojobsModule,
  ExaModule,
  FindWorkModule,
  FossJobsModule,
  FranceTravailModule,
  FreelancerComModule,
  FunctionalworksModule,
  GermantechjobsModule,
  GetOnBoardModule,
  GlassdoorModule,
  GolangJobsModule,
  GoogleModule,
  GreenJobsBoardModule,
  GuardianjobsModule,
  HabrcareerModule,
  HackerNewsModule,
  HasJobModule,
  HeadhunterModule,
  HigherEdJobsModule,
  HimalayasModule,
  IcrunchdataModule,
  IndeedModule,
  InfoJobsModule,
  IosdevjobsModule,
  JobDataApiModule,
  JobicyModule,
  JobindexModule,
  JobsAcUkModule,
  JobsChModule,
  JobsdbModule,
  JobsInJapanModule,
  JobspressoModule,
  JobstreetModule,
  JobTechDevModule,
  JoinRiseModule,
  JoobleModule,
  LandingJobsModule,
  LaraJobsModule,
  LinkedInModule,
  MonsterModule,
  MycareersfutureModule,
  NaukriModule,
  NavJobsModule,
  NoDeskModule,
  NoFluffJobsModule,
  OpensourcedesignjobsModule,
  PowertoflyModule,
  PyJobsModule,
  PythonJobsModule,
  RailsJobsModule,
  RealWorkFromAnywhereModule,
  ReedModule,
  ReliefWebModule,
  RemotefirstjobsModule,
  RemoteOkModule,
  RemotiveModule,
  SimplyHiredModule,
  SnagajobModule,
  StartupJobsModule,
  StepStoneModule,
  SwissdevjobsModule,
  TalrooModule,
  TechcareersModule,
  TeslaModule,
  TheMuseModule,
  UndpJobsModule,
  UpworkModule,
  UsajobsModule,
  VirtualVocationsModule,
  VueJobsModule,
  Web3CareerModule,
  WellfoundModule,
  WeWorkRemotelyModule,
  WordPressJobsModule,
  WorkingNomadsModule,
  ZipRecruiterModule,
];