/**
 * Hand-maintained directory of known companies per ATS platform, so the
 * admin UI can offer a "pick a company" list instead of requiring a
 * manually-typed `companySlug` / URL for every ATS search.
 *
 * **To add a company**: find its ATS's key below and append one
 * `{ name, slug }` entry to the array. Keys are every `Site` enum id that
 * is an ATS plugin (`category: 'ats'`) — all of them are pre-declared
 * here, most starting empty. `slug` is whatever that ATS plugin expects
 * for `ScraperInputDto.companySlug` — usually the company's subdomain,
 * but some platforms need a compound value (see per-key comments below,
 * e.g. Workday's `company:wdNumber:site`).
 *
 * The non-empty entries were seeded once from `docs/COMPANY_SLUG_DIRECTORY.md`
 * — that file remains the prose/human-readable reference; this file is
 * what the admin UI actually reads. The two are not auto-synced — update
 * both if you want a new entry documented there too.
 */
export interface AtsCompanyEntry {
  readonly name: string;
  readonly slug: string;
  readonly industry?: string;
}

export const ATS_COMPANY_DIRECTORY: Record<string, AtsCompanyEntry[]> = {
  greenhouse: [
    {
      name: "AccuWeather Careers",
      slug: "accuweather",
      industry: "Private-Sector Weather Forecasting",
    },
    {
      name: "ACI Learning",
      slug: "acilearning",
      industry: "IT Certification Training / Audit Education",
    },
    {
      name: "Ackermann Group",
      slug: "ackermanngroup",
      industry: "Multi-Family / Commercial Real-Estate-Services",
    },
    {
      name: "American College of Obstetricians and Gynecologists",
      slug: "acog",
      industry:
        "Medical-Specialty Membership Society / Women's-Health Clinical Guidance",
    },
    {
      name: "aCommerce",
      slug: "acommerce",
      industry: "Southeast-Asia E-commerce Enablement / Brand-Fulfilment",
    },
    {
      name: "Academy with Community Partners",
      slug: "acp",
      industry:
        "Arizona Online Instruction Charter-School / Alternative-Curriculum K-12 Education",
    },
    {
      name: "Acquia",
      slug: "acquia",
      industry:
        "Drupal-based Enterprise DXP / Open-Source-Cloud Digital Experience Platform",
    },
    {
      name: "Acrisure Innovation",
      slug: "acrisureinnovation",
      industry:
        "Insurance-Brokerage Innovation Unit / AI- and Data-Driven Broker Products",
    },
    {
      name: "Acryl Data (DataHub)",
      slug: "acryldata",
      industry: "Enterprise Metadata-Platform / Steward of Open-Source DataHub",
    },
    {
      name: "Acumen",
      slug: "acumen",
      industry:
        "Impact-Investing Nonprofit / Patient-Capital Social-Enterprise Fund + Acumen Academy Leadership Development",
    },
    {
      name: "Acurus Solutions Private Limited",
      slug: "acurussolutions",
      industry:
        "Healthcare Revenue-Cycle-Management (RCM) Outsourcing / U.S. Hospital + Physician-Group BPO (Bengaluru-HQ)",
    },
    {
      name: "Adaptive Biotechnologies",
      slug: "adaptivebiotechnologies",
      industry:
        "Commercial Immunosequencing Platform / immunoSEQ + clonoSEQ MRD Diagnostics (Seattle-HQ, NASDAQ: ADPT)",
    },
    { name: "Airbnb", slug: "airbnb", industry: "Travel / Tech" },
    { name: "Spotify", slug: "spotify", industry: "Music / Tech" },
    { name: "Discord", slug: "discord", industry: "Social / Tech" },
    { name: "SpaceX", slug: "spacex", industry: "Aerospace" },
    { name: "Cloudflare", slug: "cloudflare", industry: "Infrastructure" },
    { name: "Twilio", slug: "twilio", industry: "Communications" },
    { name: "Databricks", slug: "databricks", industry: "Data / AI" },
    { name: "Datadog", slug: "datadog", industry: "Monitoring" },
    { name: "MongoDB", slug: "mongodb", industry: "Database" },
    { name: "Elastic", slug: "elastic", industry: "Search / Analytics" },
    { name: "Snowflake", slug: "snowflakeinc", industry: "Data Cloud" },
    { name: "Roblox", slug: "roblox", industry: "Gaming" },
    { name: "Unity", slug: "unity3d", industry: "Gaming / 3D" },
    { name: "Shopify", slug: "shopify", industry: "E-commerce" },
    { name: "Canva", slug: "canva", industry: "Design" },
    { name: "Pinterest", slug: "pinterest", industry: "Social / Tech" },
    { name: "Lyft", slug: "lyft", industry: "Transportation" },
    { name: "DoorDash", slug: "doordash", industry: "Delivery" },
    { name: "Instacart", slug: "instacart", industry: "Grocery / Delivery" },
    { name: "Snap", slug: "snap", industry: "Social / Tech" },
    { name: "Rivian", slug: "rivian", industry: "Electric Vehicles" },
    {
      name: "Lucid Motors",
      slug: "lucidmotors",
      industry: "Electric Vehicles",
    },
    { name: "Block (Square)", slug: "block", industry: "Fintech" },
    { name: "Notion", slug: "notion", industry: "Productivity" },
    { name: "Stripe", slug: "stripe", industry: "Payments" },
    { name: "Coinbase", slug: "coinbase", industry: "Crypto / Finance" },
    { name: "HubSpot", slug: "hubspot", industry: "Marketing / CRM" },
    { name: "Plaid", slug: "plaid", industry: "Fintech" },
    { name: "10Alabs", slug: "10alabs" },
    { name: "Alixpartners", slug: "alixpartners" },
    { name: "Arlosolutionsllc", slug: "arlosolutionsllc" },
    { name: "Bigid", slug: "bigid" },
    { name: "Cadencesolutions", slug: "cadencesolutions" },
    { name: "Clevelandguardiansbops", slug: "clevelandguardiansbops" },
    { name: "Danieloconnellssons", slug: "danieloconnellssons" },
    { name: "Effectual", slug: "effectual" },
    { name: "Fastly", slug: "fastly" },
    { name: "Garnerhealth", slug: "garnerhealth" },
    { name: "Guild", slug: "guild" },
    { name: "Iherb", slug: "iherb" },
    { name: "Juvare", slug: "juvare" },
    { name: "Lightningai", slug: "lightningai" },
    { name: "Meridianpartners", slug: "meridianpartners" },
    {
      name: "Nationallifeinsurancecompany",
      slug: "nationallifeinsurancecompany",
    },
    { name: "Olly", slug: "olly" },
    { name: "Penninteractive", slug: "penninteractive" },
    { name: "Qualia", slug: "qualia" },
    { name: "Royalvet", slug: "royalvet" },
    { name: "Simula", slug: "simula" },
    { name: "Stemhealthcare", slug: "stemhealthcare" },
    { name: "Thatlot", slug: "thatlot" },
    { name: "Twitch", slug: "twitch" },
    { name: "Vulcanelements", slug: "vulcanelements" },
    { name: "Cresta", slug: "cresta", industry: "AI Contact Center" },
    {
      name: "Samsara",
      slug: "samsara",
      industry: "Connected Operations / IoT",
    },
    { name: "Sezzle", slug: "sezzle", industry: "BNPL Payments / Fintech" },
    {
      name: "Shopmonkey",
      slug: "shopmonkey",
      industry: "Vertical-SaaS Auto-Repair-Shop POS",
    },
    {
      name: "SimpliSafe",
      slug: "simplisafe",
      industry: "DIY Wireless Home Security",
    },
    {
      name: "Symphony Communication Services",
      slug: "symphony",
      industry: "Institutional Encrypted Collaboration",
    },
    {
      name: "Tatari",
      slug: "tatari",
      industry: "Streaming-and-Linear-TV Connected Attribution",
    },
    {
      name: "Textio",
      slug: "textio",
      industry: "Augmented-Writing / HR-Language-AI",
    },
    { name: "Nubank", slug: "nubank", industry: "Fintech / Neobank" },
    {
      name: "CookUnity",
      slug: "cookunity",
      industry: "Food-tech / Meal delivery",
    },
    { name: "Oklo", slug: "oklo", industry: "Energy / Advanced nuclear" },
    { name: "Fetch", slug: "fetch", industry: "Consumer / Loyalty & rewards" },
    { name: "Zocdoc", slug: "zocdoc", industry: "Health-tech / Marketplace" },
    { name: "Thunes", slug: "thunes", industry: "Fintech / Payments" },
    {
      name: "Strive Health",
      slug: "strivehealth",
      industry: "Health-tech / Value-based care",
    },
    { name: "Home Chef", slug: "homechef", industry: "Food-tech / Meal kits" },
    {
      name: "Pacific Fusion",
      slug: "pacificfusion",
      industry: "Energy / Fusion",
    },
    { name: "Otter.ai", slug: "otterai", industry: "AI / Productivity" },
    { name: "Observe.AI", slug: "observeai", industry: "AI / Contact center" },
    { name: "Honor", slug: "honor", industry: "Health-tech / Home care" },
    { name: "Weee!", slug: "weee", industry: "E-commerce / Grocery" },
    { name: "Narvar", slug: "narvar", industry: "E-commerce / Logistics SaaS" },
    {
      name: "Transcarent",
      slug: "transcarent",
      industry: "Health-tech / Navigation",
    },
    {
      name: "Watershed Informatics",
      slug: "watershed",
      industry: "Bio-tech / Computational biology",
    },
    { name: "Quaise Energy", slug: "quaise", industry: "Energy / Geothermal" },
    { name: "Upside", slug: "upside", industry: "Consumer / Retail tech" },
    { name: "Hungryroot", slug: "hungryroot", industry: "Food-tech / Grocery" },
    { name: "Nayya", slug: "nayya", industry: "Insurtech / Benefits" },
    {
      name: "Caribou Financial",
      slug: "caribou",
      industry: "Fintech / Lending",
    },
    {
      name: "HealthJoy",
      slug: "healthjoy",
      industry: "Health-tech / Benefits",
    },
    { name: "Papa", slug: "papa", industry: "Health-tech / Care" },
    {
      name: "AIR COMPANY",
      slug: "aircompany",
      industry: "Climate Tech / Carbon Conversion & Synthetic Fuels",
    },
    {
      name: "Arbor Energy",
      slug: "arborenergy",
      industry: "Climate Tech / Carbon-Negative Power (BECCS)",
    },
    {
      name: "Aurora Innovation",
      slug: "aurorainnovation",
      industry: "Autonomous Vehicles / Self-Driving Trucking",
    },
    {
      name: "EarnIn",
      slug: "earnin",
      industry: "Fintech / Earned-Wage Access",
    },
    {
      name: "Faraday Future",
      slug: "faradayfuture",
      industry: "Automotive / Electric Vehicles",
    },
    {
      name: "FastSpring",
      slug: "fastspring",
      industry: "Fintech / Merchant-of-Record Commerce & Subscription Billing",
    },
    {
      name: "Gravity R&D",
      slug: "gravity",
      industry: "AdTech / Recommendation & Personalization Software",
    },
    {
      name: "Runwise",
      slug: "runwise",
      industry: "Climate Tech / Smart Building Energy Management",
    },
    {
      name: "SES AI",
      slug: "sesai",
      industry: "Battery Technology / EV Energy Storage (Li-Metal)",
    },
    {
      name: "Solaris",
      slug: "solarisbank",
      industry: "Fintech / Banking-as-a-Service (Embedded Finance)",
    },
    {
      name: "Stack AV",
      slug: "stackav",
      industry: "Autonomous Vehicles / Self-Driving Trucking",
    },
    {
      name: "tastytrade",
      slug: "tastytrade",
      industry: "Fintech / Online Brokerage (Options & Futures Trading)",
    },
    {
      name: "Torc Robotics",
      slug: "torcrobotics",
      industry: "Autonomous Vehicles / Self-Driving Trucking",
    },
    {
      name: "Ursa Major",
      slug: "ursamajor",
      industry: "Aerospace & Defense / Rocket Propulsion",
    },
    {
      name: "Via",
      slug: "via",
      industry: "TransitTech / Mobility Software (SaaS + Operations)",
    },
    {
      name: "Zuora",
      slug: "zuora",
      industry: "Enterprise SaaS / Subscription Billing & Quote-to-Cash",
    },
    {
      name: "Accela",
      slug: "accela",
      industry: "Govtech (government permitting/licensing SaaS)",
    },
    {
      name: "AEVEX Aerospace",
      slug: "aevexaerospace",
      industry: "Defense aerospace (UAS, ISR, full-spectrum)",
    },
    {
      name: "Akaysha Energy",
      slug: "akayshaenergy",
      industry: "Grid/storage / grid-scale battery storage",
    },
    {
      name: "Anduril Industries",
      slug: "andurilindustries",
      industry: "Defense technology (autonomous systems, C2, counter-UAS)",
    },
    { name: "Armis", slug: "armissecurity", industry: "Asset/IoT security" },
    {
      name: "Atomic Machines",
      slug: "atomicmachines",
      industry:
        "Robotics, industrial automation, warehouse/manufacturing automation",
    },
    {
      name: "Augury",
      slug: "augury",
      industry: "Industrial IoT / machine-health sensors",
    },
    {
      name: "Aura",
      slug: "aura",
      industry: "Consumer identity / fraud protection",
    },
    {
      name: "Avantus",
      slug: "avantus",
      industry: "Clean energy / utility-scale solar & storage",
    },
    {
      name: "Avride",
      slug: "avride",
      industry:
        "Robotics, industrial automation, warehouse/manufacturing automation",
    },
    {
      name: "Axonius",
      slug: "axonius",
      industry: "Cyber asset attack surface management",
    },
    {
      name: "Beam Therapeutics",
      slug: "beamtherapeutics",
      industry: "Gene editing",
    },
    {
      name: "Blockchain.com",
      slug: "blockchain",
      industry: "Fintech — crypto wallet / exchange",
    },
    { name: "Bot Auto", slug: "botauto", industry: "Autonomous trucking" },
    {
      name: "BuildOps",
      slug: "buildops",
      industry: "Construction tech (commercial contractor management software)",
    },
    {
      name: "C3 AI",
      slug: "c3iot",
      industry: "Enterprise applied AI applications",
    },
    {
      name: "Cabify",
      slug: "cabify",
      industry: "Ride-hailing / mobility platform",
    },
    {
      name: "Cargomatic",
      slug: "cargomatic",
      industry: "Drayage / digital freight marketplace",
    },
    {
      name: "Censys",
      slug: "censys",
      industry: "Security data / applied AI platform",
    },
    {
      name: "CharterUP",
      slug: "charterup",
      industry: "Group transportation / charter mobility platform",
    },
    {
      name: "Checkbook",
      slug: "checkbook",
      industry: "Fintech — digital payments / disbursements",
    },
    {
      name: "CodePath",
      slug: "codepath",
      industry: "Edtech / tech career upskilling",
    },
    {
      name: "Cognitiv",
      slug: "cognitiv",
      industry: "Adtech (AI/deep-learning ads)",
    },
    {
      name: "Collibra",
      slug: "collibra",
      industry: "Compliance / data governance",
    },
    {
      name: "Colossal Biosciences",
      slug: "colossalbiosciences",
      industry: "Genomics / synthetic biology",
    },
    {
      name: "Customer.io",
      slug: "customerio",
      industry: "Martech (marketing automation/messaging)",
    },
    {
      name: "Cypress Creek Renewables",
      slug: "cypresscreekrenewables",
      industry: "Clean energy / utility-scale solar & storage",
    },
    {
      name: "Daybreak Game Company",
      slug: "daybreakgames",
      industry: "Gaming studios / interactive entertainment",
    },
    {
      name: "dbt Labs",
      slug: "dbtlabsinc",
      industry: "Data transformation / analytics engineering platform",
    },
    {
      name: "Dealpath",
      slug: "dealpath",
      industry:
        "Proptech / commercial real estate (deal management & investment platform)",
    },
    {
      name: "Defense Unicorns",
      slug: "defenseunicorns",
      industry: "Defense software (mission infrastructure/DevSecOps)",
    },
    {
      name: "Digital Extremes",
      slug: "digitalextremes",
      industry: "Gaming studios / interactive entertainment",
    },
    { name: "Dorsia", slug: "dorsia", industry: "Restaurant tech" },
    {
      name: "Easyship",
      slug: "easyship",
      industry: "E-commerce enablement (shipping/fulfillment SaaS)",
    },
    {
      name: "Eleventh Hour Games",
      slug: "eleventhhourgames",
      industry: "Gaming studios / interactive entertainment",
    },
    {
      name: "EMARKETER",
      slug: "emarketer",
      industry: "Martech/media (marketing research)",
    },
    {
      name: "emnify",
      slug: "emnify",
      industry: "IoT connectivity / cellular hardware-SIM platform",
    },
    {
      name: "Energy Solutions",
      slug: "energysolutions",
      industry: "Clean energy / efficiency & decarbonization services",
    },
    {
      name: "Esusu",
      slug: "esusu",
      industry:
        "Fintech — rent reporting / credit building / consumer payments",
    },
    {
      name: "Exiger",
      slug: "exiger",
      industry: "Regtech (supply-chain risk / AML / compliance)",
    },
    {
      name: "ExtraHop",
      slug: "extrahopnetworks",
      industry: "Network detection & response",
    },
    {
      name: "Federato",
      slug: "federato",
      industry: "Insurtech and insurance technology",
    },
    { name: "Feedzai", slug: "feedzai", industry: "Regtech (fraud / AML)" },
    {
      name: "Fieldwire",
      slug: "fieldwire",
      industry:
        "Construction tech (jobsite field management & coordination software)",
    },
    { name: "Flashfood", slug: "flashfood", industry: "Foodtech / food waste" },
    {
      name: "Fleetio",
      slug: "fleetio",
      industry: "Fleet management software / logistics",
    },
    { name: "Forbes", slug: "forbes", industry: "Media (publishing)" },
    { name: "Forter", slug: "forter", industry: "Fraud prevention / risk" },
    {
      name: "Freeform",
      slug: "freeformfuturecorp",
      industry: "Aerospace & defense metal additive manufacturing",
    },
    {
      name: "Galvanize Climate Solutions",
      slug: "galvanizeclimatesolutions",
      industry: "Climate tech / climate investment firm",
    },
    {
      name: "Gatik AI",
      slug: "gatikaiinc",
      industry:
        "Robotics, industrial automation, warehouse/manufacturing automation",
    },
    {
      name: "Glean",
      slug: "gleanwork",
      industry: "Enterprise AI search & assistant (applied AI)",
    },
    {
      name: "GlossGenius",
      slug: "glossgenius",
      industry: "Fintech — embedded payments / SMB platform",
    },
    {
      name: "Goodway Group",
      slug: "goodwaygroup",
      industry: "Adtech/martech (digital media agency)",
    },
    {
      name: "Gotion",
      slug: "gotion",
      industry: "Grid/storage / EV & energy-storage lithium batteries",
    },
    {
      name: "GovTech Singapore (Government Technology Agency)",
      slug: "govtech",
      industry: "Govtech (government digital services)",
    },
    {
      name: "Ghost Story Games",
      slug: "gsgcareers",
      industry: "Gaming studios / interactive entertainment",
    },
    {
      name: "Hanwha Renewables",
      slug: "hanwharenewables",
      industry: "Clean energy / utility-scale solar & storage",
    },
    {
      name: "Herald",
      slug: "heraldapi",
      industry: "Insurtech and insurance technology",
    },
    {
      name: "Homeward",
      slug: "homeward",
      industry: "Real estate tech (cash-offer home buying)",
    },
    {
      name: "Hyliion",
      slug: "hyliion",
      industry: "Electrified powertrain / clean transport",
    },
    {
      name: "Hyperproof",
      slug: "hyperproof",
      industry: "Compliance / GRC (security compliance)",
    },
    { name: "ID.me", slug: "idme", industry: "Identity verification / fraud" },
    {
      name: "InCharge Energy",
      slug: "inchargeenergy",
      industry: "Clean energy / fleet EV charging infrastructure",
    },
    { name: "Innovid", slug: "innovid", industry: "Adtech (ad serving/CTV)" },
    {
      name: "Instawork",
      slug: "instawork",
      industry: "Workforce management - hourly / flexible staffing marketplace",
    },
    {
      name: "Intrinsic",
      slug: "intrinsicrobotics",
      industry:
        "Robotics, industrial automation, warehouse/manufacturing automation",
    },
    {
      name: "Integrated Specialty Coverages",
      slug: "isccareers",
      industry: "Insurtech and insurance technology",
    },
    {
      name: "ITS Logistics",
      slug: "itslogisticsllc",
      industry: "3PL / freight / warehousing",
    },
    {
      name: "K2 Space",
      slug: "k2spacecorporation",
      industry: "Satellites (large GEO/MEO buses)",
    },
    {
      name: "Kasa",
      slug: "kasa",
      industry:
        "Proptech / real estate (tech-enabled hospitality & flexible accommodations)",
    },
    {
      name: "KH Aerospace",
      slug: "khaerospace",
      industry: "Aerospace & defense (UAS manufacturing/training)",
    },
    {
      name: "KnowBe4",
      slug: "knowbe4",
      industry: "Compliance / security awareness training",
    },
    {
      name: "Legion Technologies",
      slug: "legion",
      industry: "Workforce management software (scheduling / labor)",
    },
    {
      name: "LogicGate",
      slug: "logicgate",
      industry: "Compliance / GRC (risk management)",
    },
    {
      name: "Mark43",
      slug: "mark43",
      industry: "Govtech / public safety (police RMS/CAD)",
    },
    {
      name: "Matic Insurance",
      slug: "matic",
      industry: "Insurtech and insurance technology",
    },
    {
      name: "May Mobility",
      slug: "maymobility",
      industry: "Autonomous vehicles / mobility",
    },
    {
      name: "mediasmart",
      slug: "mediasmart",
      industry: "Adtech (omnichannel/CTV/DOOH DSP)",
    },
    {
      name: "Metropolis Technologies",
      slug: "metropolis",
      industry:
        "Proptech / real estate (AI computer-vision parking & mobility platform)",
    },
    {
      name: "MobilityWare",
      slug: "mobilityware",
      industry: "Mobile gaming / interactive entertainment",
    },
    {
      name: "Modernize Home Services",
      slug: "modernize",
      industry: "Proptech / home services (home improvement lead generation)",
    },
    {
      name: "MrBeast (Beast Industries)",
      slug: "mrbeastyoutube",
      industry: "Creator economy (media/YouTube)",
    },
    {
      name: "Nabis",
      slug: "nabis",
      industry: "Distribution / last-mile delivery",
    },
    {
      name: "NPR (National Public Radio)",
      slug: "nationalpublicradioinc",
      industry: "Media/streaming (public radio/podcasts)",
    },
    {
      name: "Neon Aerospace",
      slug: "neonaerospace",
      industry: "Aerospace (autonomous flight / propulsion)",
    },
    {
      name: "Neros Technologies",
      slug: "nerostechnologies",
      industry:
        "Robotics, industrial automation, warehouse/manufacturing automation",
    },
    {
      name: "New Leaf Energy",
      slug: "newleafenergy",
      industry: "Clean energy / solar & storage development",
    },
    {
      name: "Nex",
      slug: "nex",
      industry: "Gaming studios / interactive entertainment (motion gaming)",
    },
    {
      name: "Next Insurance",
      slug: "nextinsurance66",
      industry: "Insurtech and insurance technology",
    },
    {
      name: "Nimble Robotics",
      slug: "nimblerobotics",
      industry:
        "Robotics, industrial automation, warehouse/manufacturing automation",
    },
    {
      name: "NMI",
      slug: "nmi",
      industry: "Fintech — payments gateway / embedded payments",
    },
    {
      name: "Northspyre",
      slug: "northspyre",
      industry:
        "Proptech / real estate (development project & cost management software)",
    },
    {
      name: "Nothing",
      slug: "nothing",
      industry: "Consumer electronics (smartphones, earbuds)",
    },
    {
      name: "OneTrust",
      slug: "onetrust",
      industry: "Data privacy, security & governance",
    },
    {
      name: "OpenSpace",
      slug: "openspace",
      industry: "Construction tech (AI jobsite capture & reality mapping)",
    },
    { name: "OpenTable", slug: "opentable", industry: "Restaurant tech" },
    {
      name: "Veo",
      slug: "operationscareers",
      industry: "Shared micromobility (bikes/scooters)",
    },
    {
      name: "Orca Security",
      slug: "orcasecurity",
      industry: "Cloud security (CNAPP)",
    },
    {
      name: "Origis Energy",
      slug: "origisenergy",
      industry: "Clean energy / utility-scale solar & storage",
    },
    { name: "Osano", slug: "osano", industry: "Compliance / data privacy" },
    {
      name: "Pacvue",
      slug: "pacvue",
      industry: "E-commerce enablement / retail media SaaS",
    },
    {
      name: "Palmetto Clean Technology",
      slug: "palmettocleantech",
      industry: "Clean energy / residential solar platform",
    },
    {
      name: "Pathward",
      slug: "pathward",
      industry: "Fintech — banking-as-a-service / sponsor bank",
    },
    {
      name: "PayNearMe",
      slug: "paynearmeinc",
      industry: "Fintech — bill pay / payments platform",
    },
    {
      name: "Payoneer",
      slug: "payoneer",
      industry: "Fintech — cross-border payments",
    },
    {
      name: "Pixability",
      slug: "pixability",
      industry: "Adtech (YouTube/CTV video ads)",
    },
    {
      name: "Plus Power",
      slug: "pluspower",
      industry: "Grid/storage / standalone battery storage developer",
    },
    {
      name: "The Pokémon Company International",
      slug: "pokemoncareers",
      industry: "Gaming / interactive entertainment / esports",
    },
    { name: "Prime Medicine", slug: "primemedicine", industry: "Gene editing" },
    { name: "PubMatic", slug: "pubmatic", industry: "Adtech (SSP)" },
    {
      name: "Qualia",
      slug: "qualia",
      industry: "Real estate tech (digital closing / title & escrow platform)",
    },
    {
      name: "Razorpay",
      slug: "razorpaysoftwareprivatelimited",
      industry: "Fintech — payments gateway / banking-as-a-service",
    },
    {
      name: "Recorded Future",
      slug: "recordedfuture",
      industry: "Threat intelligence",
    },
    {
      name: "Renaissance Learning",
      slug: "renaissancelearning-nam",
      industry: "Edtech / pre-K-12 assessment & learning",
    },
    {
      name: "Riskified",
      slug: "riskified",
      industry: "Fraud prevention / e-commerce risk",
    },
    {
      name: "Rithum",
      slug: "rithum",
      industry: "E-commerce enablement / commerce network SaaS",
    },
    {
      name: "Rocket Lawyer",
      slug: "rocketlawyer",
      industry: "Legaltech (online legal services)",
    },
    { name: "Roku", slug: "roku", industry: "Media/streaming (CTV platform)" },
    {
      name: "Sana Biotechnology",
      slug: "sanabiotech",
      industry: "Cell & gene therapy",
    },
    {
      name: "Sayari",
      slug: "sayari",
      industry: "Regtech (corporate risk intelligence / AML)",
    },
    {
      name: "Scout AI",
      slug: "scoutai",
      industry: "Defense robotics / autonomous drones",
    },
    {
      name: "SecurityScorecard",
      slug: "securityscorecard",
      industry: "Compliance / cyber risk ratings",
    },
    {
      name: "SeekOut",
      slug: "seekout",
      industry: "Recruiting tech - talent sourcing & talent intelligence AI",
    },
    {
      name: "Seoul Robotics",
      slug: "seoulrobotics",
      industry:
        "Robotics, industrial automation, warehouse/manufacturing automation",
    },
    {
      name: "Shift Technology",
      slug: "shifttechnology",
      industry: "Insurtech and insurance technology",
    },
    { name: "ShipBob", slug: "shipbobinc", industry: "Fulfillment / 3PL" },
    { name: "ShipMonk", slug: "shipmonk", industry: "Fulfillment / 3PL" },
    {
      name: "Skillsoft",
      slug: "skillsoft",
      industry: "HR tech - corporate learning & talent development",
    },
    {
      name: "SmartRent",
      slug: "smartrent",
      industry:
        "Proptech (smart home & access automation for rental communities)",
    },
    {
      name: "Snorkel AI",
      slug: "snorkelai",
      industry: "Data-centric AI / data development platform",
    },
    {
      name: "Sol de Janeiro",
      slug: "soldejaneiro",
      industry: "DTC beauty brand",
    },
    {
      name: "PlayStation (Sony Interactive Entertainment)",
      slug: "sonyinteractiveentertainmentglobal",
      industry: "Gaming / interactive entertainment",
    },
    {
      name: "Speechify",
      slug: "speechify",
      industry: "Edtech / assistive learning (text-to-speech)",
    },
    {
      name: "Spin",
      slug: "spin",
      industry: "Shared micromobility (e-scooters)",
    },
    {
      name: "Splice",
      slug: "splice",
      industry: "Creator economy (music creation platform)",
    },
    { name: "SpotHopper", slug: "spothopper", industry: "Restaurant tech" },
    {
      name: "StackAdapt",
      slug: "stackadapt",
      industry: "Adtech (programmatic DSP)",
    },
    {
      name: "Starface World",
      slug: "starfaceworld",
      industry: "DTC beauty/skincare brand",
    },
    {
      name: "Stoke Space",
      slug: "stokespacetechnologies",
      industry: "Space launch (reusable rockets)",
    },
    {
      name: "Strand Therapeutics",
      slug: "strandtherapeutics",
      industry: "mRNA / synthetic biology",
    },
    {
      name: "Sumo Logic",
      slug: "sumologic",
      industry: "Security analytics (SIEM)",
    },
    {
      name: "Tebra",
      slug: "tebra",
      industry: "Digital health (practice & telehealth software)",
    },
    {
      name: "TEGNA",
      slug: "tegnainc",
      industry: "Media/streaming (broadcast TV)",
    },
    {
      name: "Tenable",
      slug: "tenableinc",
      industry: "Vulnerability & exposure management",
    },
    {
      name: "Terran Orbital",
      slug: "terranorbitalcorporation",
      industry: "Satellites (small-sat manufacturing)",
    },
    {
      name: "Tessera Therapeutics",
      slug: "tesseratherapeutics",
      industry: "Gene editing / genomics",
    },
    {
      name: "Dutchie",
      slug: "thedutchie",
      industry: "Retail tech (POS + e-commerce platform)",
    },
    {
      name: "The New York Times",
      slug: "thenewyorktimes",
      industry: "Media (news publishing)",
    },
    { name: "The Trade Desk", slug: "thetradedesk", industry: "Adtech (DSP)" },
    {
      name: "Third Wave Automation",
      slug: "thirdwaveautomation",
      industry:
        "Robotics, industrial automation, warehouse/manufacturing automation",
    },
    {
      name: "Too Good To Go",
      slug: "toogoodtogo",
      industry: "Foodtech / food waste",
    },
    {
      name: "Toradex",
      slug: "toradex",
      industry: "Embedded computing / IoT modules (SoMs)",
    },
    {
      name: "Transmit Security",
      slug: "transmitsecurity",
      industry: "Identity / fraud & CIAM",
    },
    {
      name: "True Anomaly",
      slug: "trueanomalyinc",
      industry: "Space defense / space domain awareness",
    },
    {
      name: "Picnic Delivery",
      slug: "try-picnic",
      industry: "Foodtech / food delivery",
    },
    {
      name: "Uber Freight",
      slug: "uberfreight",
      industry: "Freight marketplace / brokerage",
    },
    {
      name: "Unqork",
      slug: "unqork",
      industry: "Insurtech and insurance technology",
    },
    {
      name: "Varda Space Industries",
      slug: "vardaspace",
      industry: "Space (in-orbit manufacturing, reentry capsules)",
    },
    {
      name: "Verra Mobility",
      slug: "verramobility",
      industry: "Smart transportation / mobility tech",
    },
    {
      name: "Viant Technology",
      slug: "vianttechnology",
      industry: "Adtech (omnichannel DSP)",
    },
    {
      name: "Viral Nation",
      slug: "viralnation",
      industry: "Creator economy (influencer marketing)",
    },
    {
      name: "Vox Media",
      slug: "voxmedia",
      industry: "Media/streaming (digital publisher)",
    },
    {
      name: "VTS",
      slug: "vts",
      industry:
        "Proptech / commercial real estate (leasing & asset management platform)",
    },
    {
      name: "Wildlife Studios",
      slug: "wildlifestudios",
      industry: "Mobile gaming / interactive entertainment",
    },
    { name: "Wiz", slug: "wizinc", industry: "Cloud security (CNAPP)" },
    {
      name: "Wurl",
      slug: "wurljobs",
      industry: "Media/streaming + adtech (CTV distribution)",
    },
    {
      name: "Zynga",
      slug: "zyngacareers",
      industry: "Mobile gaming / interactive entertainment",
    },
  ],
  // Workday companySlug format: `{company}:{wdNumber}:{careerSite}`
  workday: [
    {
      name: "Salesforce",
      slug: "salesforce:12:External",
      industry: "CRM / Cloud",
    },
    { name: "Intel", slug: "intel:1:External", industry: "Semiconductors" },
    { name: "Cisco", slug: "cisco:5:Cisco_External", industry: "Networking" },
    { name: "Adobe", slug: "adobe:5:External", industry: "Software" },
    {
      name: "Epic Games",
      slug: "epicgames:5:EpicExternalSite",
      industry: "Gaming",
    },
    {
      name: "Warner Bros",
      slug: "warnerbros:5:WarnerBros",
      industry: "Entertainment",
    },
    {
      name: "Disney",
      slug: "disney:5:disneycareer",
      industry: "Entertainment",
    },
    {
      name: "Deloitte",
      slug: "deloitte:5:DeloitteUSCareers",
      industry: "Consulting",
    },
    { name: "McKinsey", slug: "mckinsey:5:External", industry: "Consulting" },
    { name: "Tesla", slug: "tesla:5:Tesla", industry: "EV / Energy" },
    {
      name: "Qualcomm",
      slug: "qualcomm:5:External",
      industry: "Semiconductors",
    },
    { name: "AMD", slug: "amd:5:External", industry: "Semiconductors" },
    {
      name: "Broadcom",
      slug: "broadcom:5:External",
      industry: "Semiconductors",
    },
    { name: "Samsung", slug: "samsung:3:Global", industry: "Electronics" },
    { name: "Siemens", slug: "siemens:3:External", industry: "Industrial" },
    {
      name: "Lockheed Martin",
      slug: "lmco:5:LMCareers",
      industry: "Aerospace / Defense",
    },
    {
      name: "Thales Group",
      slug: "thales:3:Careers",
      industry: "CRM / Cloud",
    },
  ],
  lever: [
    {
      name: "Palantir",
      slug: "palantir",
      industry: "Data Analytics / Defense",
    },
    { name: "Netflix", slug: "netflix", industry: "Streaming" },
    { name: "Atlassian", slug: "atlassian", industry: "Developer Tools" },
    { name: "Eventbrite", slug: "eventbrite", industry: "Events" },
    { name: "KPMG", slug: "kpmg", industry: "Consulting" },
    { name: "100Ms", slug: "100ms" },
    { name: "Allegiantair", slug: "allegiantair" },
    { name: "Asapp 2", slug: "asapp-2" },
    { name: "Blablacar", slug: "blablacar" },
    { name: "Cartrawler", slug: "cartrawler" },
    { name: "Coinmarketcap", slug: "coinmarketcap" },
    { name: "Deepsky", slug: "deepsky" },
    { name: "Ekohealth", slug: "ekohealth" },
    { name: "Findhelp", slug: "findhelp" },
    { name: "Glass Health Inc", slug: "glass-health-inc" },
    { name: "Hivemapper", slug: "hivemapper" },
    { name: "Jamcity", slug: "jamcity" },
    { name: "Lamudi", slug: "lamudi" },
    { name: "Madhappy", slug: "madhappy" },
    { name: "Monkshillventures", slug: "monkshillventures" },
    { name: "Numeris", slug: "numeris" },
    { name: "Peoplegrove", slug: "peoplegrove" },
    { name: "Princesspolly", slug: "princesspolly" },
    { name: "Redwoodcu", slug: "redwoodcu" },
    { name: "Sandboxvr", slug: "sandboxvr" },
    { name: "Snappr", slug: "snappr" },
    { name: "Sure", slug: "sure" },
    { name: "Thrivecausemetics", slug: "thrivecausemetics" },
    { name: "Unusual", slug: "unusual" },
    { name: "Waveapps", slug: "waveapps" },
  ],
  ashby: [
    { name: "OpenAI", slug: "openai", industry: "AI" },
    { name: "Ramp", slug: "ramp", industry: "Fintech" },
    { name: "Figma", slug: "figma", industry: "Design" },
    { name: "Linear", slug: "linear", industry: "Developer Tools" },
    { name: "Vercel", slug: "vercel", industry: "Developer Tools" },
    { name: "Plaid", slug: "plaid", industry: "Fintech" },
    { name: "Retool", slug: "retool", industry: "Developer Tools" },
    { name: "Notion", slug: "notion", industry: "Productivity" },
  ],
  // Taleo companySlug format: `{company}:{careerSection}`
  taleo: [
    {
      name: "Oracle",
      slug: "oracle:ORACLEEXT",
      industry: "Enterprise Software",
    },
    {
      name: "JPMorgan Chase",
      slug: "jpmorganchase:ExternalCareerSite",
      industry: "Banking",
    },
    {
      name: "PepsiCo",
      slug: "pepsico:ExternalSite",
      industry: "Consumer Goods",
    },
  ],
  icims: [
    { name: "EA (Electronic Arts)", slug: "ea", industry: "Gaming" },
    { name: "Goldman Sachs", slug: "goldmansachs", industry: "Banking" },
    { name: "UPS", slug: "ups", industry: "Logistics" },
  ],
  smartrecruiters: [
    { name: "Visa", slug: "Visa", industry: "Payments" },
    { name: "Bosch", slug: "BoschGroup", industry: "Industrial / Tech" },
    { name: "Equinox", slug: "Equinox", industry: "Fitness" },
    { name: "Skechers", slug: "Skechers", industry: "Footwear" },
    { name: "10Minuteschool", slug: "10minuteschool" },
    { name: "Ajua", slug: "ajua" },
    { name: "Artelia", slug: "artelia" },
    { name: "Blueally", slug: "blueally" },
    { name: "Check24", slug: "check24" },
    { name: "Continental", slug: "continental" },
    { name: "Deloittenordic", slug: "deloittenordic" },
    {
      name: "Elizabethglaserpediatricaidsfoundation3",
      slug: "elizabethglaserpediatricaidsfoundation3",
    },
    { name: "Firstdrivelogisticsinc", slug: "firstdrivelogisticsinc" },
    { name: "Ginastechjobs", slug: "ginastechjobs" },
    { name: "Hexagroup", slug: "hexagroup" },
    { name: "Ingramcontentgroup1", slug: "ingramcontentgroup1" },
    { name: "Kanadeviainova", slug: "kanadeviainova" },
    { name: "Liftedanupworkcompany", slug: "liftedanupworkcompany" },
    { name: "Mcwaneinc", slug: "mcwaneinc" },
    { name: "Mytime", slug: "mytime" },
    { name: "Nxtkeycorporation", slug: "nxtkeycorporation" },
    { name: "Primark", slug: "primark" },
    { name: "Renaud Bray", slug: "renaud-bray" },
    { name: "Samsungena", slug: "samsungena" },
    { name: "Siloamcareers", slug: "siloamcareers" },
    { name: "Sterlingenterprisellc", slug: "sterlingenterprisellc" },
    { name: "Telefonicatech", slug: "telefonicatech" },
    { name: "Trustonic", slug: "trustonic" },
    { name: "Virtuaadvancedsolution", slug: "virtuaadvancedsolution" },
  ],
  successfactors: [
    { name: "SAP", slug: "sap:SAP", industry: "Enterprise Software" },
    { name: "Accenture", slug: "accenture:Accenture", industry: "Consulting" },
    {
      name: "Siemens",
      slug: "siemens:SiemensExternal",
      industry: "Industrial",
    },
  ],
  workable: [
    { name: "Sephora", slug: "sephora", industry: "Retail / Beauty" },
    { name: "Forbes", slug: "forbes", industry: "Media" },
    { name: "Our Home", slug: "-our-home" },
    { name: "Alliedteam", slug: "alliedteam" },
    { name: "Auprosports", slug: "auprosports" },
    { name: "Blitzoo Games", slug: "blitzoo-games" },
    { name: "Cdr Companies", slug: "cdr-companies" },
    { name: "Constructor 1", slug: "constructor-1" },
    { name: "Deep Science Ventures", slug: "deep-science-ventures" },
    { name: "Elevated Hiring", slug: "elevated-hiring" },
    { name: "Fergus", slug: "fergus" },
    { name: "Gamigo", slug: "gamigo" },
    { name: "Healthsnap", slug: "healthsnap" },
    {
      name: "Infini Capital Management Limited",
      slug: "infini-capital-management-limited",
    },
    { name: "Karohealthcare", slug: "karohealthcare" },
    { name: "Lingoace", slug: "lingoace" },
    { name: "Mention Me Ltd", slug: "mention-me-ltd" },
    { name: "Nawy Real Estate", slug: "nawy-real-estate" },
    { name: "Optibpo", slug: "optibpo" },
    { name: "Pinnacle Middle East", slug: "pinnacle-middle-east" },
    { name: "Radley Yeldar", slug: "radley-yeldar" },
    { name: "Samsung Sds America", slug: "samsung-sds-america" },
    { name: "Snowed In Studios 3", slug: "snowed-in-studios-3" },
    { name: "Switchboard Hiring 1", slug: "switchboard-hiring-1" },
    { name: "Thetsuigroup", slug: "thetsuigroup" },
    {
      name: "University Of Mount Saint Vincent",
      slug: "university-of-mount-saint-vincent",
    },
    { name: "Wearenoble", slug: "wearenoble" },
  ],
  bamboohr: [
    {
      name: "StackOverflow",
      slug: "stackoverflow",
      industry: "Developer Community",
    },
    { name: "Zapier", slug: "zapier", industry: "Automation" },
    { name: "Buffer", slug: "buffer", industry: "Social Media" },
  ],
  recruitee: [
    { name: "Toggl", slug: "toggl", industry: "Productivity" },
    { name: "Hostinger", slug: "hostinger", industry: "Web Hosting" },
  ],
  manatal: [{ name: "Manatal", slug: "manatal", industry: "HR Tech" }],
  paylocity: [
    {
      name: "(Discover from company career page URL pattern: `recruiting.paylocity.com/Recruiting/Jobs/Details/{guid}`)",
      slug: "",
    },
  ],
  phenom: [
    { name: "Boeing", slug: "boeing", industry: "Aerospace" },
    { name: "Hilton", slug: "hilton", industry: "Hospitality" },
    { name: "Nestle", slug: "nestle", industry: "Consumer Goods" },
    { name: "Comcast", slug: "comcast", industry: "Telecom" },
    { name: "Verizon", slug: "verizon", industry: "Telecom" },
  ],
  bullhorn: [
    {
      name: "(Discover from staffing agency career portal source code)",
      slug: "",
    },
  ],
  avature: [
    { name: "Bloomberg", slug: "bloomberg", industry: "Financial Data" },
    {
      name: "KPMG Ireland",
      slug: "kpmgireland",
      industry: "Professional Services",
    },
    {
      name: "Deloitte (PNG)",
      slug: "deloittepng",
      industry: "Professional Services",
    },
    { name: "Maximus", slug: "maximus", industry: "Government Services" },
    { name: "Plante Moran", slug: "plantemoran", industry: "Accounting" },
    { name: "NVA (Vet Group)", slug: "nva", industry: "Veterinary" },
    { name: "Delta", slug: "delta", industry: "Aviation" },
    {
      name: "One800Flowers",
      slug: "one800flowers",
      industry: "Retail / E-commerce",
    },
    { name: "Ally", slug: "ally", industry: "Banking / Finance" },
    { name: "Astellas", slug: "astellas", industry: "Pharmaceuticals" },
    { name: "Bupa ANZ", slug: "bupaanz", industry: "Healthcare / Insurance" },
    { name: "CBRE Global", slug: "cbreglobal", industry: "Real Estate" },
    {
      name: "GPS Hospitality",
      slug: "gpshospitality",
      industry: "Restaurants / Franchising",
    },
    {
      name: "Monadelphous",
      slug: "monadelphous",
      industry: "Engineering / Construction",
    },
    {
      name: "Resource Bank",
      slug: "resourcebank",
      industry: "Financial Services",
    },
  ],
  gem: [
    { name: "Accel", slug: "accel", industry: "Venture Capital" },
    { name: "43North", slug: "43north", industry: "Startup Accelerator" },
    {
      name: "8020 Consulting",
      slug: "8020-consulting",
      industry: "Consulting",
    },
    {
      name: "A16Z Speedrun",
      slug: "a16z-speedrun",
      industry: "Venture Capital",
    },
    { name: "Acre", slug: "acre", industry: "Climate / Sustainability" },
    { name: "Agora", slug: "agora", industry: "Real Estate Tech" },
    { name: "Airframe", slug: "airframe", industry: "Developer Tools" },
    {
      name: "Alex and Ani",
      slug: "alex-and-ani",
      industry: "Retail / Jewelry",
    },
    { name: "11X AI", slug: "11x-ai", industry: "AI / SaaS" },
    {
      name: "10X Construction AI",
      slug: "10xconstruction-ai",
      industry: "Construction Tech",
    },
    { name: "Aarden AI", slug: "aarden-ai", industry: "AI / Sales" },
    { name: "Acely", slug: "acely", industry: "Education Tech" },
    { name: "Afterquery", slug: "afterquery", industry: "AI / Data" },
    { name: "Agenta AI", slug: "agenta-ai", industry: "LLM Ops" },
  ],
  join_com: [
    { name: "Awork", slug: "awork", industry: "Productivity / SaaS" },
    { name: "Alteos", slug: "alteos", industry: "Insurance Tech" },
    { name: "Aitad", slug: "aitad", industry: "AI / Data" },
    { name: "Capitalmind", slug: "capitalmind", industry: "Asset Management" },
    {
      name: "Brandcircle",
      slug: "brandcircle",
      industry: "Marketing / E-commerce",
    },
    { name: "Cinnamood", slug: "cinnamood", industry: "Food / Hospitality" },
    { name: "Brandneo", slug: "brandneo", industry: "Marketing" },
    {
      name: "Brunathelabel",
      slug: "brunathelabel",
      industry: "Fashion / Apparel",
    },
    { name: "Allunity", slug: "allunity", industry: "Crypto / DeFi" },
    {
      name: "Citychickennhas490",
      slug: "citychickennhas490",
      industry: "Restaurants / QSR",
    },
    { name: "Caiz", slug: "caiz", industry: "Crypto / Fintech" },
    { name: "Cannaleo", slug: "cannaleo", industry: "Cannabis Retail" },
    {
      name: "Big City Beats",
      slug: "bigcitybeats",
      industry: "Music / Events",
    },
    { name: "AXSOL", slug: "axsol", industry: "Power / Energy Storage" },
    {
      name: "Career Sancovia",
      slug: "career-sancovia",
      industry: "Career Services",
    },
  ],
  oracle: [
    { name: "Oracle", slug: "eeho-us2", industry: "Enterprise Software" },
    { name: "City of Atlanta", slug: "ehxr-us2", industry: "Government" },
    { name: "TTX", slug: "ejjc-us6", industry: "Rail / Logistics" },
    {
      name: "CooperCompanies",
      slug: "hcjy-us2",
      industry: "Healthcare / MedTech",
    },
    { name: "EXP", slug: "elcn-us2", industry: "Engineering Consulting" },
    { name: "Kroll", slug: "hcxs-us2", industry: "Risk / Financial Advisory" },
    { name: "Macy's", slug: "ebwh-us2", industry: "Retail" },
    { name: "Westpac Group", slug: "ebuu-ap1", industry: "Banking" },
    { name: "DTCC", slug: "ebxr-us2", industry: "Financial Infrastructure" },
    { name: "Hologic", slug: "ebwb-us2", industry: "Medical Devices" },
    { name: "Mountaire", slug: "ebtg-us2", industry: "Food / Poultry" },
    { name: "Mouser", slug: "eabw-us2", industry: "Electronics Distribution" },
    { name: "Ricoh", slug: "cbha-us2", industry: "Imaging / Technology" },
    { name: "Galliford Try", slug: "cbct-em2", industry: "Construction" },
    { name: "Apollo Hospitals", slug: "cgs-ap2", industry: "Healthcare" },
  ],
  mercor: [
    { name: "Stripe", slug: "stripe", industry: "Payments" },
    { name: "OpenAI", slug: "openai", industry: "AI / Foundation Models" },
    {
      name: "Anthropic",
      slug: "anthropic",
      industry: "AI / Foundation Models",
    },
    { name: "Notion", slug: "notion", industry: "Productivity SaaS" },
    { name: "Airbnb", slug: "airbnb", industry: "Travel / Marketplace" },
    { name: "Figma", slug: "figma", industry: "Design Tools" },
    { name: "Vercel", slug: "vercel", industry: "Developer Infrastructure" },
    { name: "Linear", slug: "linear", industry: "Productivity / DevTools" },
    { name: "Discord", slug: "discord", industry: "Social / Communication" },
    { name: "Coinbase", slug: "coinbase", industry: "Crypto / Finance" },
    { name: "Plaid", slug: "plaid", industry: "Fintech / Open Banking" },
    { name: "Ramp", slug: "ramp", industry: "Fintech / Spend Management" },
  ],
  tesla: [
    { name: "Tesla", slug: "tesla", industry: "Electric Vehicles / Energy" },
    { name: "Upstart", slug: "upstart", industry: "Fintech / AI Lending" },
    { name: "Tamara", slug: "tamara", industry: "Fintech / BNPL" },
    {
      name: "TrueLayer",
      slug: "truelayer",
      industry: "Fintech / Open Banking",
    },
    { name: "Public", slug: "public", industry: "Fintech / Retail Investing" },
    { name: "Paystack", slug: "paystack", industry: "Fintech / Payments" },
    {
      name: "Moniepoint",
      slug: "moniepoint",
      industry: "Fintech / Business Banking",
    },
    {
      name: "Thrive Market",
      slug: "thrivemarket",
      industry: "E-commerce / Online Grocery",
    },
    {
      name: "Form3",
      slug: "form3",
      industry: "Fintech / Payments Infrastructure",
    },
    {
      name: "Marvel Fusion",
      slug: "marvelfusion",
      industry: "Energy / Fusion",
    },
    {
      name: "Kairos Power",
      slug: "kairospower",
      industry: "Energy / Advanced Nuclear",
    },
    { name: "Wolt", slug: "wolt", industry: "Food Delivery / Local Commerce" },
    {
      name: "Redwood Materials",
      slug: "redwoodmaterials",
      industry: "Energy / Battery Materials",
    },
    {
      name: "Group14 Technologies",
      slug: "group14",
      industry: "Energy / Battery Materials",
    },
    {
      name: "Carbon",
      slug: "carbon",
      industry: "Manufacturing / Additive Manufacturing",
    },
    {
      name: "Forward",
      slug: "forward",
      industry: "Digital Health / Primary Care",
    },
    { name: "Tia", slug: "tia", industry: "Digital Health / Women’s Health" },
    {
      name: "Headway",
      slug: "headway",
      industry: "Digital Health / Mental Health",
    },
    {
      name: "Talkspace",
      slug: "talkspace",
      industry: "Digital Health / Mental Health",
    },
    {
      name: "Octave",
      slug: "octave",
      industry: "Digital Health / Mental Health",
    },
    { name: "Freenome", slug: "freenome", industry: "Biotech / Diagnostics" },
    {
      name: "Natera",
      slug: "natera",
      industry: "Biotech / Genetic Diagnostics",
    },
    {
      name: "Generate Biomedicines",
      slug: "generatebiomedicines",
      industry: "Biotech / AI Drug Discovery",
    },
    { name: "Oura", slug: "oura", industry: "Consumer Health Hardware" },
    { name: "Carvana", slug: "carvana", industry: "E-commerce / Auto Retail" },
    {
      name: "unybrands",
      slug: "unybrands",
      industry: "E-commerce / Brand Aggregator",
    },
    { name: "Yotpo", slug: "yotpo", industry: "MarTech / E-commerce" },
    { name: "TaxBit", slug: "taxbit", industry: "Fintech / Crypto Tax" },
    {
      name: "Culture Amp",
      slug: "cultureamp",
      industry: "HR Tech / People Analytics",
    },
    {
      name: "Energage",
      slug: "energage",
      industry: "HR Tech / Employee Engagement",
    },
    { name: "Veriff", slug: "veriff", industry: "Identity / KYC" },
    { name: "Thoropass", slug: "thoropass", industry: "Security / Compliance" },
    { name: "Endor Labs", slug: "endorlabs", industry: "Security / AppSec" },
    { name: "Cybereason", slug: "cybereason", industry: "Security / Endpoint" },
    {
      name: "Tanium",
      slug: "tanium",
      industry: "Security / Endpoint Management",
    },
    { name: "Expel", slug: "expel", industry: "Security / MDR" },
    { name: "Figure", slug: "figureai", industry: "Humanoid Robotics / AI" },
    {
      name: "Slice",
      slug: "slice",
      industry: "SMB Fintech / Restaurant Technology",
    },
    {
      name: "Chowbus",
      slug: "chowbus",
      industry: "Restaurant Technology / Food Delivery",
    },
    {
      name: "TabaPay",
      slug: "tabapay",
      industry: "Payments / Fintech Infrastructure",
    },
    {
      name: "PathAI",
      slug: "pathai",
      industry: "Healthcare AI / Digital Pathology",
    },
    {
      name: "Found",
      slug: "found",
      industry: "SMB Fintech / Business Banking",
    },
    {
      name: "Parsley Health",
      slug: "parsleyhealth",
      industry: "Healthcare / Telehealth",
    },
    {
      name: "Neuralink",
      slug: "neuralink",
      industry: "Neurotechnology / Brain-Computer Interface",
    },
    { name: "CLEAR", slug: "clear", industry: "Identity / Biometric Security" },
  ],

  // No known companies yet for the platforms below — add entries as you
  // find them (see the file header for the format).
  adp: [],
  akkencloud: [],
  altamira: [],
  applicantpro: [],
  applicantstack: [],
  applied: [],
  apploi: [],
  arcoro: [],
  avionte: [],
  beamery: [],
  beesite: [],
  beetween: [],
  beisen: [],
  bizneo: [],
  brassring: [],
  breathehr: [],
  breezyhr: [],
  careerplug: [],
  carerix: [],
  catsone: [],
  ceipal: [],
  cezanne: [],
  clearcompany: [],
  cleverconnect: [],
  comeet: [],
  concludis: [],
  connexys: [],
  cornerstone: [],
  crelate: [],
  cvwarehouse: [],
  darwinbox: [],
  dayforce: [],
  deel: [],
  digitalrecruiters: [],
  dover: [],
  dvinci: [],
  easycruit: [],
  eddy: [],
  eightfold: [],
  elmo: [],
  employmenthero: [],
  emply: [],
  eploy: [],
  exacthire: [],
  expr3ss: [],
  factorial: [],
  flatchr: [],
  fountain: [],
  freshteam: [],
  gohire: [],
  greeting: [],
  greythr: [],
  gupy: [],
  harri: [],
  heyrecruit: [],
  hibob: [],
  hireful: [],
  hirehive: [],
  hireology: [],
  hireserve: [],
  hiringthing: [],
  homerun: [],
  hreasily: [],
  hron: [],
  hrone: [],
  hrpartner: [],
  inrecruiting: [],
  ismartrecruit: [],
  isolved: [],
  jazzhr: [],
  jobadder: [],
  jobdiva: [],
  jobscore: [],
  jobsoid: [],
  jobtoolz: [],
  jobtrain: [],
  jobvite: [],
  jobylon: [],
  keka: [],
  kenjo: [],
  livehire: [],
  loxo: [],
  mindscope: [],
  mokahr: [],
  namely: [],
  niceboard: [],
  occupop: [],
  oleeo: [],
  oorwin: [],
  otys: [],
  pageup: [],
  paychex: [],
  paycom: [],
  paycor: [],
  pcrecruiter: [],
  peoplefluent: [],
  // PeopleHR companySlug is the subdomain at `{slug}.peoplehr.net`.
  peoplehr: [
    {
      name: "CBM Global",
      slug: "cbmglobal",
      industry: "HR Tech / Employee Engagement",
    },
  ],
  peoplestrong: [],
  personio: [],
  pinpoint: [],
  polymer: [],
  prescreen: [],
  pyjamahr: [],
  radancy: [],
  reachmee: [],
  recooty: [],
  recruitcrm: [],
  recruiterflow: [],
  recruiteze: [],
  recruitis: [],
  recruitly: [],
  rexx: [],
  roubler: [],
  sagehr: [],
  sagepeople: [],
  scouttalent: [],
  sense: [],
  sesamehr: [],
  skeeled: [],
  snaphunt: [],
  softgarden: [],
  softy: [],
  solides: [],
  subscribehr: [],
  sympa: [],
  symphonytalent: [],
  taleez: [],
  talentadore: [],
  talentera: [],
  talentlyft: [],
  talentreef: [],
  talentsoft: [],
  teamdash: [],
  teamtailor: [],
  tempworks: [],
  trackerrms: [],
  traffit: [],
  trakstar: [],
  tribepad: [],
  turbohire: [],
  ukg: [],
  umantis: [],
  varbi: [],
  vidcruiter: [],
  vincere: [],
  vivahr: [],
  webcruiter: [],
  workatastartup: [],
  workforce: [],
  workstream: [],
  workwise: [],
  wttj: [],
  zimyo: [],
  zohorecruit: [],
  zwayam: [],
};
